# Generated by Django 3.2.5 on 2021-07-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addpeople', '0002_alter_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
