# Generated by Django 3.2.5 on 2021-07-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addpeople', '0011_auto_20210723_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='person',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='person',
            name='sex',
        ),
    ]
